const express = require("express") 
const router = express.Router() 
const AdminController = require("../controller/adminController") 
const FileController = require("../controller/fileController")
router.get("/dashboard" , AdminController.checkIfLogin ,  AdminController.getAdmin)  
router.get("/login" , AdminController.getLogin) 
router.post("/login" , AdminController.handleLogin)
router.get("/blog-admin/register" , AdminController.getAdminRegistration)  
router.post("/blog-admin/register" , AdminController.handleRegister) 
router.get("/dashboard" , AdminController.checkIfLogin , AdminController.getAdmin)
router.get("/admins" , AdminController.checkIfLogin , AdminController.getAllAdmin) 
router.get("/settings" , AdminController.checkIfLogin , AdminController.getAdminSetting) 
router.post("/profile/update" ,AdminController.checkIfLogin ,  AdminController.updateAdminInformation) 
router.post("/profile/avatar" , AdminController.checkIfLogin , FileController.userUpload.single("avatar") ,  AdminController.handleUpdateAvatar) 

router.get("/categories" ,AdminController.checkIfLogin ,  AdminController.getCategories)  
router.post("/categories" ,AdminController.checkIfLogin ,  AdminController.createCategory) 
router.get("/categories/:categoryName" , AdminController.checkIfLogin , AdminController.deletePostCategory)   
router.post("/categories/:categoryName" ,AdminController.checkIfLogin ,  AdminController.updatePostCategory)  
router.get("/posts" , AdminController.checkIfLogin , AdminController.getCreatePost)
router.post("/posts" , AdminController.handleCreatePost) 
//router.get("/bigjara-admin" , AdminController.getBigjaraPortal)  
router.get("/posts/:title" , AdminController.checkIfLogin , AdminController.getSinglePost)  
router.post("/posts/:title" , AdminController.checkIfLogin ,   FileController.userUpload.single("avatar")  , AdminController.updateAndPublishPost) 
router.get("/posts/:id/delete" , AdminController.checkIfLogin ,    AdminController.deletePost)
router.get("/posts/fetch/:id" ,AdminController.checkIfLogin ,  AdminController.fetchPost) 
router.get("/logout" , AdminController.handleLogout)
module.exports = router