const express = require("express") 
const router = express.Router() 
const BlogController = require("../controller/blogController")
router.get("/" , BlogController.getHome) 
router.get("/u/login" , BlogController.getUserLogin) 
router.post("/u/login" , BlogController.handleUserLogin) 
router.get("/u/register" , BlogController.getRegistration) 
router.post("/u/login" , BlogController.handleRegistration) 
router.get("/u/dashboard" , BlogController.getUserDashboard) 
//router.get("/:category" , BlogController.getCategory)
router.get("/:category/:post" ,BlogController.getPost ) 
router.post("/:category/:post" ,BlogController.addComment )  
router.post("/post/update" , BlogController.updatePost) 
module.exports = router